### ISSUE TITLE
Support Single Fixture File Loading

### ISSUE THREAD

**Issue by daino3** [go-testfixtures/testfixtures#1]
It doesn't appear this functionality is available. Can I suggest it as a feature?

Example (just add a singularized version of the existing LoadFixtures method)

``` golang
testfixtures.LoadFixture("../fixtures/<my-table>.yml", db, &testfixtures.MySQLHelper{})
```

**Comment by andreynering** [comment]
I see no problem allowing that. I'll do when possible.

**Comment by andreynering** [comment]
I implemented `LoadFixtureFiles`. I made it variadic, so it accepts how many files you want (but will work with a single one).

``` go
testfixtures;LoadFixtureFiles(db, &PostgreSQLHelper{},
    "fixtures/customers.yml", "fixtures/orders.yml", ...)
```
