### ISSUE TITLE
Can I use JSON files for fixtures?

### ISSUE THREAD

**Issue by renanbastos93** [go-testfixtures/testfixtures#154]
I saw this project but it focuses on using YAML, we can implement the JSON?
Another point, how to ignore fixture in binary?

**Comment by andreynering** [comment]
Hi @renanbastos93,

In theory, YAML is a superset of JSON, so you can try to write JSON but save as an `.yml` file. We don't have official support to JSON.

About ignoring, I'm not sure if I understood what you meant, but as the README says you can `testfixtures.Files` to load specific files if you don't want to load a full directory.

Let me know if you have any further questions.

**Comment by renanbastos93** [comment]
@andreynering 

Of course, thanks a lot for your reply quickly.
Well, I will try to explain again.

1. How do to ignore fixture files when building the app?
2. As we don't have official support for JSON, maybe can we implement it? What do you think about it?

see ya
best regards

**Comment by andreynering** [comment]
Sorry, but I still don't understand what you mean by "ignore on the binary" or "ignore when building". Fixtures are usually kept in a separate directory, and are not included into the binary (or are you using [`embed`](https://pkg.go.dev/embed))? Also, it's meant to be used for tests. Are you trying to do something different here?

Regarding JSON support, not planned at the moment, specially because we are tightly dependent on the YAML library at the moment.

**Comment by renanbastos93** [comment]
@andreynering 

I am so sorry I did confuse you, my English is not so good. But I did a mistake you are right fixtures are no entries on binary only can use the case we use to embed.

About JSON, I can help you to put on here. Can I study this approach? Later I could open a PR.

**Comment by andreynering** [comment]
No problem.

Actually, seems that we don't have that much YAML specific code as I thought.

We'd need to address `yaml.Unmarshal` calls [like this one](https://github.com/go-testfixtures/testfixtures/blob/d37f09b51c0f0a38e201ea7cd3cb198fc0b1fd9a/testfixtures.go#L468).

I believe it should probably be done automatically based on the extension of the file: `.json`: parse as JSON, `.yaml`: parse as YAML.

**Comment by renanbastos93** [comment]
Alright, I will do some tests later and will be thinking of a solution to that.
