### ISSUE TITLE
Errors are sometimes swallowed incorrectly in databaseName

### ISSUE THREAD

**Issue by jeffmeyers** [go-testfixtures/testfixtures#17]
I ran into an issue recently where my database had run out of connections but I received an error from testfixtures that my database name didn't include "test." This is a bit misleading and took me some time to track down.

How do you feel about modifying the helper interface to return `(string, error)`? This matches other methods on the interface and while it would be a breaking change it could help folks track down errors more easily when they occur.

Happy to PR this if you think it's a sane move. Thanks for the library!

**Comment by andreynering** [comment]
Yes, it's reasonable to return an error there. A PR would be welcome.
