### ISSUE TITLE
Support TiDB

### ISSUE THREAD

**Issue by tetsumaru** [go-testfixtures/testfixtures#180]
In my environment I get the following error when initializing test fixtures.
```
"You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 8 near \"CHECKSUM TABLE `sample_table`\""
```

It seems that TiDB does not support CHECKSUM TABLE.
https://docs.pingcap.com/tidbcloud/dev-guide-third-party-tools-compatibility#tidb-does-not-support-the-check-table-statement

We [avoid this problem](https://github.com/go-testfixtures/testfixtures/blob/fe28dd81bb4290e21f425c65e83c1747252400bf/mysql.go#L119-L159) by forking testfixtures and commenting out the "CHECKSUM TABLE" so that it is not used.

I would like to be able to use test-fixtures in TiDB without forking and commenting out.

**Comment by codeit14** [comment]
I'm facing the same issue as well, would it be possible to support for it

**Comment by slsyy** [comment]
@codeit14 #206 is merged and released. Could you verify, if it works for you?

**Comment by tetsumaru** [comment]
@codeit14 @slsyy 
I was able to resolve this issue in my local environment with v3.12.0 by adding the following:
```
testfixtures.New(
    ...
    testfixtures.SkipTableChecksumComputation(),
)
```

Thank you.
