### ISSUE TITLE
`Load()` calculate hash of every table at the end and I don't know why

### ISSUE THREAD

**Issue by slsyy** [go-testfixtures/testfixtures#203]
v3.11.0

The last function call for `Load()`:
https://github.com/go-testfixtures/testfixtures/blob/b1fe75b2f31f9af027da52787e7c2892f9703c47/testfixtures.go#L460

and postgres implementation

https://github.com/go-testfixtures/testfixtures/blob/b1fe75b2f31f9af027da52787e7c2892f9703c47/postgresql.go#L362-L376

Basically it iterates over the whole database (in my case it is 100+ tables) and calculate md5 hash of each table for no reason. Do I miss something or maybe it can be removed? In my case it slows down tests in noticeable way

**Comment by slsyy** [comment]
Oh I see, it make sense for subsequent `Load` calls.

Do you think it make sense to make some flag to disable this behavior? In my case I use `Load` only once per loader, because I use https://github.com/DATA-DOG/go-txdb , which perform cleanup automatically

**Comment by andreynering** [comment]
Hi @slsyy,

We already have [DangerousSkipCleanupFixtureTables](https://pkg.go.dev/github.com/go-testfixtures/testfixtures/v3#DangerousSkipCleanupFixtureTables). Can you try and see if it works for you?

I'm not sure if it _also_ skips the checksum computing for all tables, but if not it would make sense to fix that IMO.

**Comment by slsyy** [comment]
@andreynering this flag control that piece of code:

https://github.com/go-testfixtures/testfixtures/blob/b1fe75b2f31f9af027da52787e7c2892f9703c47/testfixtures.go#L420-L430

where I want to skip this:

https://github.com/go-testfixtures/testfixtures/blob/b1fe75b2f31f9af027da52787e7c2892f9703c47/testfixtures.go#L460


Reason: In my code I use this library in such a way:

```golang
	fixtures, err := testfixtures.New(...)
	handleErr(t, err)
	handleErr(fixtures.Load());
	// and fixtures object dies here
```

so I basically don't need all of those hashes, because they won't be used anyway, if I don't call `Load()` more than once. With `txdb` anyway it doesn't make sense as `tx.Rollback` revert all the changes

I can raise a PR, if it make sense

**Comment by andreynering** [comment]
@slsyy I'm not so sure if we could do the fix for the existing `DangerousSkipCleanupFixtureTables` flag, or if we'd need a new flag this. I'd need to revisit the code to be sure.

Anyway, feel free to open a PR with a proposal if you want to!
