### ISSUE TITLE
Regression in reset sequence for MySQL

### ISSUE THREAD

**Issue by Gusted** [go-testfixtures/testfixtures#212]
Hi,

For the Forgejo project, an automatic dependency update PR was opened for testfixtures to version `v3.12.0` from `v3.11.0` and [the CI caught an error](https://codeberg.org/forgejo/forgejo/actions/runs/23108/jobs/7#jobstep-7-118) that was related to the update:

```
LoadFixtures failed after retries: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `issue` AUTO_INCREMENT = 10000;ALTER TABLE `issue_label` AUTO_INCREM' at line 1
```

This looks like to be a regression from #208. It seems like MySQL doesn't allow multiple `ALTER` statements in one go.

**Comment by andreynering** [comment]
Hi @Gusted,

Can you add the `multiStatements` parameters like this?:

https://github.com/go-testfixtures/testfixtures/blob/98baced6f3905ea319026663731723f8612903d2/.sample.env#L2

That parameter is required, and we have that [documented on the README](https://github.com/go-testfixtures/testfixtures?tab=readme-ov-file#mysql--mariadb).

**Comment by nannany** [comment]
I was also getting the following error, but by putting the `multiStatements=true` option, it worked. Thank you very much.

```
Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE ~~~
```

**Comment by andreynering** [comment]
I'm closing for now, but if anyone has any thoughts, feel free to add.
