### ISSUE TITLE
Error 1064 (42000) on v3.12.0

### ISSUE THREAD

**Issue by mrehanabbasi** [go-testfixtures/testfixtures#235]
After upgrading to `v3.12.0`, I'm getting this error on `loader.Load()`:

```
Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `<table-name>` AUTO_INCREMENT = 10000' at line 1
```

It worked fine till `v3.11.0` but as soon as the `testfixtures` package is updated, it starts giving this error.

**Database:** MySQL 8.0.35
**Driver:** github.com/go-sql-driver/mysql v1.8.1

**Comment by slsyy** [comment]
Check, if you open the db connection in mode, which support multiple statement in one query https://github.com/go-testfixtures/testfixtures?tab=readme-ov-file#mysql--mariadb

In previous version multistatements were not used, so it was not necessary. Now we use it for faster database setup https://github.com/go-testfixtures/testfixtures/commit/6d9bdb684a5dc2e03a6acf2fd552b39abb658739

**Comment by mrehanabbasi** [comment]
@slsyy Yeah, adding `multiStatements=true` to the connection string did the trick. Thanks.
