### ISSUE TITLE
MySQL doesn't support multiple statements

### ISSUE THREAD

**Issue by wxiaoguang** [go-testfixtures/testfixtures#240]
This change is not right. MySQL doesn't work that way.

```
LoadFixtures failed after retries: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `issue` AUTO_INCREMENT = 10000;ALTER TABLE `release` AUTO_INCREMENT ' at line 1
```

_Originally posted by @wxiaoguang in https://github.com/go-testfixtures/testfixtures/pull/208#discussion_r1823778648_

----

Well ... see the REAMDE: `?multiStatements=true` but it is not a good approach. It makes the tests different from the production config.

The `testfixtures` should use the same connection parameters as production IMO

**Comment by slsyy** [comment]
I will think about solution

> The testfixtures should use the same connection parameters as production IMO

You can use a separate connection for `testfixtures`. It won't work in transaction though

**Comment by slsyy** [comment]
Fixed in https://github.com/go-testfixtures/testfixtures/pull/249 , released in https://github.com/go-testfixtures/testfixtures/releases/tag/v3.14.0
