### ISSUE TITLE
Split database supports into separate packages?

### ISSUE THREAD

**Issue by wxiaoguang** [go-testfixtures/testfixtures#241]
Recently go-testfixtures got clickhouse support, and there would be more in the future, that's cool and really useful.

Meanwhile, for most users, they only need to work with one or a few databases, so the huge dependencies introduced by clickhouse seems redundant.

Could the core go-testfixtures be kept tiny and simple, and introduce new database supports by new packages? eg:

```
import (
  "github.com/go-testfixtures/testfixtures"
  "github.com/go-testfixtures/testfixtures-clickhouse"
)
```

**Comment by slsyy** [comment]
The current bloat is only due to test dependencies. Right now the library code uses only these dependencies

```
require (
	golang.org/x/sync v0.8.0
	gopkg.in/yaml.v3 v3.0.1
)

require (
	github.com/kr/pretty v0.3.1 // indirect
	github.com/rogpeppe/go-internal v1.10.0 // indirect
	gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c // indirect
)
``` 
(will be pursued in https://github.com/go-testfixtures/testfixtures/issues/215)

Support by package would be nice due to:
* better modularity
* possibility to write your own driver without forking this repo

On the other hand it is a pretty breaking change. Let's see in the future, if there is a need for such an approach

**Comment by ccoVeille** [comment]
What about using interfaces?

This way the package doesn't depend on something before it gets used.

It's what is implemented in gofr.

- https://github.com/gofr-dev/gofr/pull/736/files

**Comment by slsyy** [comment]
> This way the package doesn't depend on something before it gets used.

As I said: all implementations on drivers operate on `*sql.Db`, which means library could provide hundreds of them and bloat on end-user is minimal

One could argue, that code size increase, but I thinks it's pretty negligible

I think there is some value to move all drivers to a separate packages, but I need to research, if it does not break backwards compatibility

**Comment by wxiaoguang** [comment]
I give up, it bloats the binary about several metabytes in my case, will remove the go-testfixtures dependency, then it won't bother me.

----

The bloat could/would be fixed by  "chore: remove ClickHouse underscore import #220" and "chore: remove spanner underscore import #250", but I have written my own fixture importer, no need to worry about these import tricks.

**Comment by slsyy** [comment]
@wxiaoguang ty for the information, i didn't know, that those `_` imports are so heavy

**Comment by lansfy** [comment]
> I give up, it bloats the binary about several metabytes in my case, will remove the go-testfixtures dependency, then it won't bother me.

@wxiaoguang , you can use copy of "testfixtures" from my library

https://github.com/lansfy/gonkex/tree/master/storage/addons/sqldb/testfixtures

I removed all third-party dependencies and tests, so now it's lightweight. And return to the original when the problem with dependencies will be solved.

**Comment by slsyy** [comment]
@wxiaoguang @lansfy i removed all underscore imports from the lib. The total trim (so also `go.mod` file) is planned for the next release
