### ISSUE TITLE
Allow use of templates inside YAML files

### ISSUE THREAD

**Issue by s-takehana** [go-testfixtures/testfixtures#25]
I want to use like ERB/[Ego](https://github.com/benbjohnson/ego) to create large data.

```erb
<% 1000.times do |n| %>
user_<%= n %>:
  username: <%= "user#{n}" %>
  email: <%= "user#{n}@example.com" %>
<% end %>
```

**Comment by andreynering** [comment]
Hi @s-takehana, thanks for your feature request!

Nice feature, but I think it's better to use Go's own templates language than ERB. Specially because ERB on Go requires code generation, so not easy to implement. Still a nice feature to have, though.
