### ISSUE TITLE
Use "TRUNCATE" instead of "DELETE FROM" for better performance

### ISSUE THREAD

**Issue by andreynering** [go-testfixtures/testfixtures#26]
It's available for PG, not sure for other databases:

https://www.postgresql.org/docs/9.6/static/sql-truncate.html

**Comment by vendion** [comment]
It's also available for MySQL/MariaDB and also resets at least MySQL/MariaDB's primary key counter.

**Comment by andreynering** [comment]
I think it's better not to fix what isn't broken in the first place. 😉

Seems that `DELETE FROM` is usually faster than `TRUNCATE TABLE` for small tables: https://stackoverflow.com/a/11423886
