### ISSUE TITLE
Can't unload or load empty table

### ISSUE THREAD

**Issue by hamid-elaosta** [go-testfixtures/testfixtures#3]
Some of my tests require that my queries return zero results because the DB is empty.

If I don't call load on my first test, I can get this behaviour, however on subsequent runs, due to having loaded in a later test, this test now fails (more than zero results) as the sqlite DB still exists.

It'd be helpful to have an unload/reset or a way to load in an empty table using the NewFiles for this purpose.

**Comment by andreynering** [comment]
If you have the following content on the file it will just delete all records:

```yml
# mytable.yml
[]
```

Does this resolve you use case?

**Comment by hamid-elaosta** [comment]
Hi, yes it appears to solve the issue, but requires a slightly different implementation to that documented. I have to have two functions `prepareDatabase` and `prepareEmptyDatabase`. I move the NewFolder creation from the TestMain to these functions and call them on `testdata/fixtures` and `testdata/empty` then I call the functions as required for each test.

Yes it works, but it doesn't seem clean or correct. Thank you however for the quick solution.

**Comment by andreynering** [comment]
So you just want to clean a single table instead of loading the fixtures again?

If you wanted to load fixtures *and* also clean that table, than you could just create the file in your existing folder.

I may add a function to do that, but you can also just run `DELETE FROM table`.

**Comment by hamid-elaosta** [comment]
Not exactly, I'll try to elaborate;

The tests are testing an API, it's important that I test the APIs response for no items, one item and multiple items.

For a single table, I have a fixture with 3 items. What's the best way to also test one item and no items?

Depending on the order I run the tests, I may need to unload/reload a single table from my fixture sets.

I guess I could delete/add manually, I can't quite decide on the cleanest solution.

**Comment by andreynering** [comment]
In the end you will decide the approach that work for you. =)

I think of fixtures as sample data that is useful for most tests. But, for some tests you will eventually have to insert more specific data manually. (Maybe some day I find a way to make these situations easier with this package.)

What you can try is having different scenarios for different users. E.g. a user with no item, other with one, and still other with many, etc.

**Comment by hamid-elaosta** [comment]
Great thanks. I think given that you've answered the question in the title, it should be safe to close this.
