### ISSUE TITLE
wanted public method CheckDatabaseName

### ISSUE THREAD

**Issue by corvinusy** [go-testfixtures/testfixtures#35]
Sometimes it is need to make db schema initialization before texture uploading.
And this method will be helpful to unify database name checking.

**Comment by andreynering** [comment]
Hi @corvinusy,

This is an easy one. Contributions are welcome

**Comment by corvinusy** [comment]
proposing #36

**Comment by andreynering** [comment]
@corvinusy Thanks for contributing!

Closing since #36 is merged
