### ISSUE TITLE
JSONB types in Postgres

### ISSUE THREAD

**Issue by heynemann** [go-testfixtures/testfixtures#4]
Whenever I add to a fixture a map or array, I get an error like:

```
"sql: converting Exec argument #3's type: unsupported type map[interface {}]interface {}, a map"
```

Any chance we can support JSONB?

**Comment by andreynering** [comment]
I haven't tried JSONB before, but I just did a fast search and I think it will be trivial to support.

http://coussej.github.io/2016/02/16/Handling-JSONB-in-Go-Structs/

**Comment by heynemann** [comment]
That would DEFINITELY improve our fixtures. Congrats on the lib anyways! :)

**Comment by andreynering** [comment]
Closed by https://github.com/go-testfixtures/testfixtures/pull/5

Let me know if it works for you.

**Comment by heynemann** [comment]
I'll try tomorrow! Thank you SO MUCH!

Bernardo Heynemann
