### ISSUE TITLE
DB Connection Refused

### ISSUE THREAD

**Issue by Fyb3roptik** [go-testfixtures/testfixtures#44]
Using Postgres I can connect to the database fine using sql.Open, but passing the variable to testfixtures produces this error:

```
dial tcp [::1]:5432: connect: connection refused
```

Here is my code:

```go
dbConnectionString := os.Getenv("DATABASE_TEST_CONNECTION_STRING")
db, err := sql.Open("postgres", dbConnectionString)
if err != nil {
	log.Println("DEBUG: ERROR ", err)
}

_, err = testfixtures.NewFolder(db, &testfixtures.PostgreSQLHelper{}, "testdata")
 if err != nil {
     log.Println("DEBUG: ", err)
 }
```

**Comment by andreynering** [comment]
Hi @Fyb3roptik.

> Using Postgres I can connect to the database fine using sql.Open

My guess is that you don't. `sql.Open` validates the connection string, but doesn't try to connect to the database.

Try this before running textfixtures:

```go
if err := db.Ping(); err != nil {
        panic(err)
}
```

`Ping` really tries to connect to the database, and you're likely to get an error if the connection string is wrong.
