### ISSUE TITLE
fixtures.Load is not working 

### ISSUE THREAD

**Issue by mouli1382** [go-testfixtures/testfixtures#45]
I generated the fixtures using GenerateFixtures API with my postgres development database. Got the fixtures under the testdata/fixtures folder.

After that I have been trying to load those fixtures into a test database and run my tests but fixtures.Load() call is failing as I don't see any relations in the database and thus all my tests are failing.

Do suggest if I am missing anything.

**Comment by andreynering** [comment]
Hi @mouli1382,

As mentioned in the README, the feature that generates data based on an existing database is experimental. It's very possible there're incompatibilities and you may need to manually edit the fixtures to fix them.

Maybe if you post the error message here I'd be able to help a bit more.

**Comment by andreynering** [comment]
Ping @mouli1382

**Comment by andreynering** [comment]
Closed for lack of feedback
