### ISSUE TITLE
Can't correctly load binary data from generated yml file

### ISSUE THREAD

**Issue by craig08** [go-testfixtures/testfixtures#48]
I use SQLite3 to store small binary data (data type `blob`). Call `GenerateFixtures()` and obtain a `.yml` file like following:
```
- type: 0
  value:
  - 8
  - 128
  - 8
  - 16
  - 13
...
```

When I use `Load()` to read this `*.yml` file and overwrite the whole DB entries, the values are not the same as they were when I generated the fixtures. Except for `blob`, other data types remain intact.

Before `GenerateFixtures()`:
```
INSERT INTO logs VALUES(2,1024,1,X'088008100d18a4f3f488a8c3aad015','2019-05-21 17:55:01.882239396+08:00',NULL,0,0);
```

After `Load()`:
```
INSERT INTO logs VALUES(2,1024,1,X'5b382c3132382c382c31362c31332c32342c3136342c3234332c3234342c3133362c3136382c3139352c3137302c3230382c32315d','2019-05-21 17:55:01.882239396+08:00',NULL,0,0);
```

I believe the inconsistency is caused by `json.Marshal` in `jsonArray`'s receiver function `Value()`. It will automatically convert `[]int` to marshaled `[]byte`, but the result is unexpected.

An easy workaround is like this:
```
func (a jsonArray) Value() (driver.Value, error) {
    var arr []byte
    for _, v := range a {
        arr = append(arr, byte(v.(int)))
    }
    return arr, nil
}
```
However, it just considers int array case.

Any suggestions?

**Comment by andreynering** [comment]
Hi @craig08,

Thanks for opening this issue!

As the README says, generating fixtures is an experimental feature. In some cases it's expected that you'll have to manually edit your fixtures to became valid.

That said, sure we can improve it. 🙂

Your proposed solution is likely on the right way, i.e. we likely need a custom marshaler or unmarshaler to handle binary data.

**Comment by KoduIsGreat** [comment]
any update on this issue? I run into a similar issue with postgres, I have a table that stores blob data (i.e a zip) the binary data that goes into the yaml is incorrect making it invalid.

**Comment by andreynering** [comment]
Hi @KoduIsGreat,

Sorry, this is still an issue, but contributions are welcome!

**Comment by andreynering** [comment]
We just implemented support for binary data in master. It's working for both the load and dump processes, and it uses the `0x[hex]` format.

Thanks @d1m1ch for contributing with this!
