### ISSUE TITLE
 Support Clickhouse

### ISSUE THREAD

**Issue by tlightsky** [go-testfixtures/testfixtures#51]
load data to clickhouse
driver: https://github.com/kshvakov/clickhouse

**Comment by andreynering** [comment]
Hi @tlightsky,

I don't plan to implement this myself unless there's enough interest (ClickHouse is not as popular as the currently supported databases).

This is open for contributions, though.

**Comment by shumorkiniv** [comment]
Hello! Not so long ago I came face to face with this problem. So I decided to solve it. [Here](https://github.com/go-testfixtures/testfixtures/pull/115) is my pull request.
