### ISSUE TITLE
Is it possible to use this plugin with Gorm ?

### ISSUE THREAD

**Issue by xoco70** [go-testfixtures/testfixtures#52]
Hi, 

I'm using Gorm as ORM and I wanted to know if I could test my postgres queries in sqlite with testfixtures ?

Thanks for this nice plugin !

**Comment by andreynering** [comment]
Hi @xoco70,

Yes, it for sure is. I used it with Gorm myself in the past.

Actually, testfixtures only use standard library (+ the driver for your database), and doesn't care for which ORM you use (if any).

**Comment by andreynering** [comment]
Sorry, I think I misread your question (read the title and forget the body).

> I'm using Gorm as ORM and I wanted to know if I could test my postgres queries in sqlite with testfixtures?

So, in theory you could use PostgreSQL in production, but still run your tests on SQLite. I *definitely* do not recommend that, though!

There are differences between databases (be syntax, behavior, etc) and you should ideally test using the same database you use in production.

**Comment by bastengao** [comment]
`*gorm.DB.DB()` returns `*sql.DB`
