### ISSUE TITLE
How do I install this package?

### ISSUE THREAD

**Issue by ChiliConSql** [go-testfixtures/testfixtures#64]
I get the following error when using "go get ":

> can't load package: package github.com/go-testfixtures/testfixtures: code in directory /home/im
> ad/.go/src/github.com/go-testfixtures/testfixtures expects import "github.com/go-testfixtures/t
> estfixtures/v3"

**Comment by ChiliConSql** [comment]
I guess I need to learn about modules...:-(

**Comment by johnrazeur** [comment]
I've got exactly the same problem.
