### ISSUE TITLE
Support for PostGIS fields?

### ISSUE THREAD

**Issue by sazary** [go-testfixtures/testfixtures#7]
Hi  
I'm struggling to find out how can I use a PostGIS field in my fixtures. For example, for updating my model I need to run this command:

```
update my_table set polygon = ST_GeomFromText("SRID=4326; POLYGON ((11 22, 33 44, 55 66))") where id = 1;
```

and in my fixtures I have:

```
- id: 1
  polygon: ST_GeomFromText("SRID=4326; POLYGON ((11 22, 33 44, 55 66))")
```

But in the SQL command it executes, it wraps `ST_GeomFromText...` in quotations, which results in error.  
How can I tell it not to wrap some value in quotations?  

Thanks.

**Comment by andreynering** [comment]
This is now possible. Prefix a value with `RAW=` to write raw SQL in a fixture:

```yml
- id: 1
  polygon: RAW=ST_GeomFromText("SRID=4326; POLYGON ((11 22, 33 44, 55 66))")
```

**Comment by sazary** [comment]
thank you andrey!
