### ISSUE TITLE
Add support for "pgx" postgres driver/dialect.

### ISSUE THREAD

**Issue by richard-to** [go-testfixtures/testfixtures#71]
I'm currently using `pgx` (https://github.com/jackc/pgx) instead of `pq` I would like to use this driver/dialect in testfixtures, but it's not currently supported. Seems like I can just add `pgx` to the `helperForDialect` function. I tested it out and it seemed to work. It also passed the unit tests.

There was one slight difference that I noticed. In one of my fixtures I have a zip code string field, which I populate like this `11111`. In `postgres`/`pq` it gets converted to a string automatically. But I noticed in `pgx` I need to explicitly make the zip code a string (e.g. `'11111'`). There may be more differences, but haven't tested it too extensively so far.

```golang
func helperForDialect(dialect string) (helper, error) {
	switch dialect {
	case "postgres", "postgresql", "timescaledb", "pgx":
		return &postgreSQL{}, nil
	case "mysql", "mariadb":
		return &mySQL{}, nil
	case "sqlite", "sqlite3":
		return &sqlite{}, nil
	case "mssql", "sqlserver":
		return &sqlserver{}, nil
	default:
		return nil, fmt.Errorf(`testfixtures: unrecognized dialect "%s"`, dialect)
	}
}
```

**Comment by andreynering** [comment]
Hi @richard-to,

Great to know it kinda already works!

I think it's just a matter adding `pgx` to this `switch` as you said, and making sure there's a test for it.

**Comment by richard-to** [comment]
Ok, great, I'll see if I can spin up a pull request next time I get the chance.

**Comment by andreynering** [comment]
Closed as part of #74.

**Comment by ChiliConSql** [comment]
Hey guys, do you have an example of how to use this in code?

**Comment by richard-to** [comment]
> Hey guys, do you have an example of how to use this in code?

I believe you can set "pgx" as the dialect.

Here's a snippet from the readme.md that I modified:

```golang
        fixtures, err = testfixtures.New(
                testfixtures.Database(db), // You database connection
                testfixtures.Dialect("pgx"),
                testfixtures.Directory("testdata/fixtures"), // the directory containing the YAML files
        )
```

There's a comment there that says: `// Available: "postgresql", "timescaledb", "mysql", "mariadb", "sqlite" and "sqlserver"` So that can be updated I think to include pgx.

**Comment by ChiliConSql** [comment]
Thank you @richard-to . My confusion was how to get the "db" connection. It has to be stdlib.Conn and not pgx.Conn, correct?

**Comment by richard-to** [comment]
Yes, you're right. You'll have to use `database/sql` with the pgx dialect . This should be fine since it's only for doing simple operations to manage the fixtures.

I do something like this in my code:

```
db, err = sql.Open(testConfig.Database.Dialect(), testConfig.Database.ConnectionInfo())
```

Then for my tests I use pgx directly. In my case I use pgxpool.

```
pool, err = pgxpool.Connect(context.Background(), testConfig.Database.ConnectionInfo())
```

**Comment by richard-to** [comment]
Though I guess if you're using some very specific postgres features that don't work with database/sql, then this approach may not work
