### ISSUE TITLE
Reset MySQL autoincrement?

### ISSUE THREAD

**Issue by vikke** [go-testfixtures/testfixtures#79]
Can this product truncate table before insert yaml?
Now table's auto increments is not cleared.
I want reset auto increment value when insert yaml.

I'm using mysql.

thanks.

**Comment by andreynering** [comment]
Hi @vikke,

We do something similar with PostgreSQL sequences. I didn't know it was also needed to reset MySQL autoincrement values... I thought it was handled automatically by MySQL.
