### ISSUE TITLE
can the entire table data be deleted and modified to delete the corresponding data

### ISSUE THREAD

**Issue by CottonChou** [go-testfixtures/testfixtures#86]
Now when importing data, the data in the relevant table will be deleted. This approach is a bit rude (for example, some data I don’t want to delete or others want to use the data), can it be modified to delete the data that conflicts with the imported data (For example, specify a single primary key？). I know this is a bit more complicated than deleting the entire table, but generally speaking, we expect to delete this part of the data that we imported.

**Comment by fr3fou** [comment]
Did you figure out a solution?
