### ISSUE TITLE
UseDropConstraint() not applied and tests failed because of relational constrains

### ISSUE THREAD

**Issue by yuseferi** [go-testfixtures/testfixtures#99]
Hi there, 
my postgres is version 10.10 and my golang is 1.15.
I used the following config to initial fixtures,

	f, err := testfixtures.New(
		testfixtures.Database(db),
		testfixtures.Dialect("postgresql"),
		testfixtures.Directory("../fixtures"),
		testfixtures.DangerousSkipTestDatabaseCheck(),
		testfixtures.UseDropConstraint(),
	)

with `UseDropConstraint` still, I'm getting foreign key constraint 

17:37:27      XXXXXXXXX.go:412: testfixtures: error inserting record: ERROR: insert or update on table "XXXXXXXXX" violates foreign key constraint "XXXXXXXXX_fk" (SQLSTATE 23503)
( X are masked character)

any thought and idea why it's not applied and I see the error.

Thanks

**Comment by andreynering** [comment]
Hi @yuseferi,

Unfortunately with the given information I can't know what exactly is happening. I you happen to discover, please let me know.

Alternatively, you could try `UseAlterConstraint`: https://github.com/go-testfixtures/testfixtures#with-alter-constraint
